# Generated by Django 3.0.7 on 2020-06-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200605_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto')], max_length=5),
        ),
    ]
